DROP TABLE [Bank].[Transaction]
DROP TABLE [Bank].[Accounts]
DROP TABLE [Bank].[Customers]
DROP TABLE [Bank].[AccountType]



IF NOT EXISTS (SELECT 1			  
			   FROM 
				INFORMATION_SCHEMA.SCHEMATA
			  WHERE 
				SCHEMA_NAME = 'Bank')
BEGIN
	EXEC ('CREATE SCHEMA Bank')
END	

IF NOT EXISTS(SELECT 1
			  FROM 
				INFORMATION_SCHEMA.TABLES
			  WHERE 
				TABLE_SCHEMA = 'Bank'
				AND TABLE_NAME = 'Customers')
BEGIN 
	CREATE TABLE [Bank].[Customers](
		[id] [INT] IDENTITY(1,1) NOT NULL,
		[FirstName] [VARCHAR](50) NOT NULL,
		[LastName] [VARCHAR](50) NOT NULL,
		[Jmbg] [CHAR](13) NOT NULL,
		[City] [VARCHAR](50) NOT NULL,
		[PostalCode] [VARCHAR](50) NOT NULL,
		[HouseNumber] [VARCHAR](15) NOT NULL,
	 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
	(
		[Jmbg]
	)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END	

IF NOT EXISTS(SELECT 1
			  FROM 
				INFORMATION_SCHEMA.TABLES
			  WHERE 
				TABLE_SCHEMA = 'Bank'
				AND TABLE_NAME = 'Accounts')
BEGIN	
	CREATE TABLE [Bank].[Accounts](
		[id] [INT] IDENTITY(1,1) NOT NULL,
		[AccountNumber] [BIGINT] NOT NULL,
		[AccountTypeId] [INT] NOT NULL,
		[CustomerJmbg] [CHAR] (13) NOT NULL,
	 CONSTRAINT [UN_Accounts_id] UNIQUE 
	(
		[id] ASC
	),
	CONSTRAINT [PK_AccountNumber] PRIMARY KEY CLUSTERED 
	(
		[AccountNumber]
	)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END	

IF NOT EXISTS(SELECT 1
			  FROM 
				INFORMATION_SCHEMA.TABLES
			  WHERE 
				TABLE_SCHEMA = 'Bank'
				AND TABLE_NAME = 'AccountType')
BEGIN	
	CREATE TABLE [Bank].[AccountType](
		[id] [INT] IDENTITY(1,1) NOT NULL,
		[AccountTypeName] [VARCHAR] (30) NOT NULL,
	CONSTRAINT [PK_AccountTypeId] PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END	

IF NOT EXISTS(SELECT 1
			  FROM 
				INFORMATION_SCHEMA.TABLES
			  WHERE 
				TABLE_SCHEMA = 'Bank'
				AND TABLE_NAME = 'Transaction')
BEGIN	
	CREATE TABLE [Bank].[Transaction](
		[id] [INT] IDENTITY(1,1) NOT NULL,
		[AccountId] [INT] NOT NULL,
		[Valuee] [BIGINT] NOT NULL,
		[PositiveNegative] [CHAR] (1) NOT NULL
	CONSTRAINT [PK_TransactionId] PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END	

IF EXISTS(SELECT 1
			  FROM 
				INFORMATION_SCHEMA.TABLES
			  WHERE 
				TABLE_SCHEMA = 'Bank'
				AND TABLE_NAME = 'Accounts')
BEGIN
	ALTER TABLE [Bank].[Accounts] WITH CHECK ADD CONSTRAINT [FK_AccountTypeId] FOREIGN KEY ([AccountTypeId])
	REFERENCES [Bank].[AccountType]([id])
	ALTER TABLE [Bank].[Accounts] WITH CHECK ADD CONSTRAINT [FK_AccountCustomerJmbg] FOREIGN KEY ([CustomerJmbg])
	REFERENCES [Bank].[Customers]([jmbg])
	ALTER TABLE [Bank].[Accounts] WITH CHECK ADD CONSTRAINT [CHECK_AccountNumber] CHECK (([AccountNumber])>999999999999999 AND ([AccountNumber]<10000000000000000))
END

IF EXISTS(SELECT 1
			  FROM 
				INFORMATION_SCHEMA.TABLES
			  WHERE 
				TABLE_SCHEMA = 'Bank'
				AND TABLE_NAME = 'Transaction')
BEGIN
	ALTER TABLE [Bank].[Transaction] WITH CHECK ADD CONSTRAINT [FK_AccountId] FOREIGN KEY ([AccountId])
	REFERENCES [Bank].[Accounts] ([Id])
END
